# Generated by Django 5.0.7 on 2024-07-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('young_specialist', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE VIEW young_specialists_view AS
            SELECT 
                ROW_NUMBER() OVER() AS id,
                org.name,
                mi.article_name,
                ml.target_distribution_count,
                ml.distribution_count,
                mh.start_date,
                mh.end_date
            FROM 
                Young_Specialist_MonthlyFormHeader mh
            JOIN 
                Young_Specialist_MonthlyFormLine ml ON mh.id = ml.header_id
            JOIN 
                Young_Specialist_YoungSpecialistIndicators mi ON ml.indicator_id = mi.id
             JOIN 
                Young_Specialist_Organization org ON mh.organization_id = org.id;
            """,
            reverse_sql="DROP VIEW IF EXISTS young_specialists_view;"
        ),
    ]
